## 내부 클래스(ineer class)
- 클래스 안의 클래스
```java
class A {       // 외부 클래스
    ...
    class B {   // 내부 클래스
        ...     
    }
}
```
- 내부 클래스의 장점
    - 내부 클래스에서 외부 클래스의 멤버들을 쉽게 접근할 수 있다. 
        - 객체 생성 없이도 내부 클래스가 외부클래스의 멤버 접근 가능
    - 코드의 복잡성을 줄일 수 있다. (캡슐화)

## 내부 클래스의 종류와 특징
- 내부 클래스의 종류와 유효범위(scope)는 변수와 동일
```java
class Outer {
    int iv = 0;
    static cv = 0;
    void myMethod() {
        int lv = 0;
    }
}

class Outer {
    class InstanceInner {}
    static class StaticInner {}

    void myMethod() {
        class LocalInner {}
    }
}
```
|내부 클래스|특징|
|---|---|
|인스턴스 내부 클래스|외부 클래스의 멤버변수 선언위치에 선언하며, 외부 클래스의 인스턴스멤버처럼 다루어진다. <br>주로 외부 클래스의 인스턴스 멤버들과 관련된 작업에 사용될 목적으로 선언된다.|
|스태틱 내부 클래스|외부 클래스의 멤버변수 선언위치에 선언하며, 외부 클래스의 static멤버처럼 다루어진다. <br>주로 외부 클래스의 static멤버, 특히 static메서드에서 사용될 목적으로 선언된다.|
|지역 내부 클래스|외부 클래스의 메서드나 초기화블럭 안에 선언하며, 선언된 영역 내부에서만 사용될 수 있다.|
|익명 클래스|클래스의 선언과 객체의 생성을 동시에 하는 이름없는 클래스(일회용)|

## 내부 클래스의 제어자와 접근성
- 내부 클래스의 제어자는 변수에 사용가능한 제어자 4개 모두 사용 가능
- ex 1.
```java
class Ex7_12 { 
	class InstanceInner { // 인스턴스 내부 클래스
		int iv = 100; 
		static int cv = 100;            // 에러! static변수를 선언할 수 없다. 
		final static int CONST = 100;   // final static은 상수이므로 static 붙이는거 허용
	} 

   	static class StaticInner { // static 내부 클래스에서는 외부 클래스의 인스턴스 멤버에 접근 불가능
		int iv = 200; 
		static int cv = 200;    // static클래스만 static멤버를 정의할 수 있다. 
	} 

	void myMethod() {   // 지역 내부 클래스
		class LocalInner { 
			int iv = 300; 
			static int cv = 300;             // 에러! static변수를 선언할 수 없다. 
			final static int CONST = 300;    // final static은 상수이므로 static 붙이는거 허용 
		} 
	}
} 
```
- ex 2.
```java
class Ex7_13 {
	class InstanceInner {}
	static class StaticInner {}

	// 인스턴스멤버 간에는 서로 직접 접근이 가능하다.
	InstanceInner iv = new InstanceInner();
	// static 멤버 간에는 서로 직접 접근이 가능하다.
	static StaticInner cv = new StaticInner();

	static void staticMethod() {
      // static멤버는 인스턴스멤버에 직접 접근할 수 없다.
//		InstanceInner obj1 = new InstanceInner();	
		StaticInner obj2 = new StaticInner();

      // 굳이 접근하려면 아래와 같이 객체를 생성해야 한다.
      // 인스턴스클래스는 외부 클래스를 먼저 생성해야만 생성할 수 있다.
		Ex7_13 outer = new Ex7_13();
		InstanceInner obj1 = outer.new InstanceInner();
	}

	void instanceMethod() {
      // 인스턴스메서드에서는 인스턴스멤버와 static멤버 모두 접근 가능하다.
		InstanceInner obj1 = new InstanceInner();
		StaticInner obj2 = new StaticInner();
		// 메서드 내에 지역적으로 선언된 내부 클래스는 외부에서 접근할 수 없다.
//		LocalInner lv = new LocalInner();
	}

	void myMethod() {
		class LocalInner {}
		LocalInner lv = new LocalInner();
	}
}
```
- ex 3.
```java
class Outer {
	private int outerIv = 0;
	static  int outerCv = 0;

	class InstanceInner {
		int iiv  = outerIv;  // 외부 클래스의 private멤버도 접근가능하다.
		int iiv2 = outerCv;
	}

	static class StaticInner {
// 스태틱 클래스는 외부 클래스의 인스턴스멤버에 접근할 수 없다.
//		int siv = outerIv;
		static int scv = outerCv;
	}

	void myMethod() {
		int lv = 0;
		final int LV = 0;  // JDK1.8부터 final 생략 가능

		class LocalInner {
			int liv  = outerIv;
			int liv2 = outerCv;
//	외부 클래스의 지역변수는 final이 붙은 변수(상수)만 접근가능하다.
//			int liv3 = lv;	// 에러!!!(JDK1.8부터 에러 아님)
			int liv4 = LV;	// OK
		}
	}
}

```
- ex3의 포인트 2개
    - 내부클래스에서 외부 클래스의 private 멤버도접근 가능하다. 
    - 지역변수는 메서드 종료와 함께 소멸되고  
    메서드 내의 내부 클래스의 객체가 지역변수보다 더 오래 존재할 수도 있으므로  
    외부 클래스의 지역변수를 사용하려면 final이 붙은 변수(상수)만 접근 가능하다.
        - JDK 1.8부터는 final 안붙은 변수인데 값이 바뀐적 없으면 상수로 취급한다.
        - 상수는 constant pool에서 따로 존재하기 때문에 메서드 종료와 상관없이 계속 사용 가능하다.

- ex 4.
	- 문법적인 내용은 그냥 문법이니까 왜그런지 이해하려 하지말고 걍 보기
```java
class Outer2 {
	class InstanceInner {
		int iv = 100;
	}

	static class StaticInner {
		int iv = 200;
		static int cv = 300;
	}

	void myMethod() {
		class LocalInner {
			int iv = 400;
		}
	}
}

class Ex7_15 {
	public static void main(String[] args) {
		// 인스턴스클래스의 인스턴스를 생성하려면
		// 외부 클래스의 인스턴스를 먼저 생성해야 한다.
		Outer2 oc = new Outer2();
		Outer2.InstanceInner ii = oc.new InstanceInner();

		System.out.println("ii.iv : "+ ii.iv);
		System.out.println("Outer2.StaticInner.cv : "+Outer2.StaticInner.cv);
                                     
	   // 스태틱 내부 클래스의 인스턴스는 외부 클래스를 먼저 생성하지 않아도 된다.
		Outer2.StaticInner si = new Outer2.StaticInner();
		System.out.println("si.iv : "+ si.iv);
	}
}
```
이 예제를 컴파일하면 5개의 클래스가 만들어진다.
```java
Ex7_15.class
Outer2.class
Outer2$InstanceInner.class
Outer2$StaticInner.class
Outer2$1LocalInner.class	// 지역 클래스는 숫자 붙음
```
- ex 5.
	- this 쓰는 방법
```java
class Outer3 {
	int value = 10;	// Outer3.this.value

	class Inner {
		int value = 20;   // this.value

		void method1() {
			int value = 30;
			System.out.println("            value :" + value);	// 가까운거. 30
			System.out.println("       this.value :" + this.value);	// 20
			System.out.println("Outer3.this.value :" + Outer3.this.value);	// 10
		}
	} // Inner클래스의 끝
} // Outer3클래스의 끝

class Ex7_16 {
	public static void main(String args[]) {
		Outer3 outer = new Outer3();
		Outer3.Inner inner = outer.new Inner();
		inner.method1();
	}
}
```

## 익명 클래스(anonymous class)
- 이름이 없는 일회용 클래스. 정의와 생성을 동시에
```java
new 조상클래스이름() {
	// 멤버 선언
}
	
	또는

new 구현인터페이스이름() {
	// 멤버 선언
}
```

<br>

- 예제 1
```java
class Ex7_17 {
	Object iv = new Object(){ void method(){} };         // 익명 클래스
	static Object cv = new Object(){ void method(){} };  // 익명 클래스

	void myMethod() {
		Object lv = new Object(){ void method(){} };      // 익명 클래스
	}
}
```
컴파일 시 생기는 클래스
```java
Ex7_17.class
Ex7_17$1.class
Ex7_17$2.class
Ex7_17$3.class
```
- 예제 2
```java
import java.awt.*;
import java.awt.event.*;

class Ex7_18 {
	public static void main(String[] args) {
		Button b = new Button("Start");
		b.addActionListener(new EventHandler());
	}
}

class EventHandler implements ActionListener {
	public void actionPerformed(ActionEvent e) {
		System.out.println("ActionEvent occurred!!!");
	}
}
```
어차피 한번만 쓰고 말 클래스를 아래와 같이 익명 클래스로 만든다.
```java
import java.awt.*;
import java.awt.event.*;

class Ex7_19 {
	public static void main(String[] args) {
		Button b = new Button("Start");
		b.addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent e) {
					System.out.println("ActionEvent occurred!!!");
				}
			} // 익명 클래스의 끝
		);
	} // main의 끝
} 
```

# Ch08
## 프로그램 오류
- 컴파일 에러(compile-time error): 컴파일할 때 발생하는 에러
- 런타임 에러(runtime error): 실행할 때 발생하는 에러	
	- 프로그램이 종료됨
- 논리적 에러(logical error): 작성 의도와 다르게 동작
	- 프로그램이 종료되진 않음
### Java의 런타임 에러
- 에러(error): 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 예외(exception): 프로그램 코드에 의해 수습될 수 있는 다소 미약한 오류
### 예외처리의 정의와 목적
- 정의: 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
- 목적: 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것
### Exception과 RuntimeException
- Exception클래스들: 		사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
- RuntimeException클래스들: 프로그래머의 실수로 발생하는 예외
### 정리
- 프로그램 오류
	- 컴파일 에러
		- 이클립스에서 빨간줄 뜨는거
	- 런타임 에러
		- Error
		- Exception
			- Exception과 그 자손들
			- RuntimeException과 그 자손들
	- 논리적 에러

## 예외 처리하기. try-catch문
```java
try {
	// 예외가 발생할 가능성이 있는 문장들을 넣는다.
} catch (Exception1 e1) {
	// Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
} catch (Exception2 e2) {
	// Exception2이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
} catch (ExceptionN eN) {
	// ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
}
```
- if문과 달리, try블럭이나 catch블럭 내에 포함된 문장이 하나뿐이어도 괄호{}를 생략할 수 없다.
### try-catch문에서의 흐름
1. try블럭 내에서 예외가 발생한 경우
	1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
	2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행한다.  
	만일 일치하는 catch블럭을 찾지 못하면, 예외는 처리되지 못한다.
2. try블럭 내에서 예외가 발생하지 않은 경우
	1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.
### 예외의 발생과 catch블럭
- 예외가 발생하면, 이를 처리할 catch블럭을 찾아 내려감
- 일치하는 catch블럭이 없으면, 예외는 처리 안됨
- Exception이 선언된 catch블럭은 모든 예외를 처리할 수 있음
	- 마지막 catch블럭에 사용
```java
class Ex8_4 {
	public static void main(String args[]) {
		System.out.println(1);			
		System.out.println(2);
		try {
			System.out.println(3);
			System.out.println(0/0);
			System.out.println(4); 	// 실행되지 않는다.
		} catch (ArithmeticException ae)	{
			if (ae instanceof ArithmeticException) 
				System.out.println("true");	
			System.out.println("ArithmeticException");
		} catch (Exception e){	// 모든 예외 처리 가능
			System.out.println("Exception");
		}	// try-catch의 끝
		System.out.println(6);
	}	// main메서드의 끝
}
```
output
```
1
2
3
true
ArithmeticException
6
```

## printStackTrace()와 getMessage()
예외가 발생하면 예외 객체가 생성되고 예외 객체 안의 메서드들로 예외에대한 정보를 얻을 수 있다.

- printStackTrace(): 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
- getMessage(): 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.
## 멀티 catch블럭
- 내용이 같은 catch블럭을 하나로 합친 것
```java
try {
	...
} catch (ExceptionA e) {
	e.printStackTrace();
} catch (ExceptionB e2) {
	e2.printStackTrace();
}
```
위와 같이 내용이 같은 catch블럭을 하나로 합쳐보면
```java
try {
	...
} catch (ExceptionA | ExceptionB e) {
	e.printStackTrace();
}
```
- 멀티 catch블럭에 쓰이는 클래스가 부모 자식관계면 에러가 생긴다.
	- 부모 클래스로만 catch해도 됨
```java
try {
	...
// } catch (ParentException | ChildException e) {...} // 에러
} catch (ParentException e) {	// 위의 라인과 의미상 동일하며 정상작동
	...
}
```
- 둘 중 하나의 예외에만 있는 메서드 호출 불가 (조건문 이용해 호출)
	- instanceof로 체크 후 형변환해서 사용
```java
try {
	...
} catch (ExceptionA | ExceptionB e) {
	e.methodA();	// 에러. ExceptionA에만 선언된 메서드 호출 불가

	if (e instanceof ExceptionA) {
		ExceptionA e1 = (ExceptionA)e;	// 형변환
		e1.methodA();
	} else {/* if (e instanceof ExceptionB) */}
}
```
## 예외 발생시키기
1. 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
`Exception e = new Exception("고의로 발생시켰음");`
2. 키워드 throw를 이용해 예외를 발생시킨다.
`throw e;`

```java
class Ex8_6 {
	public static void main(String args[]) {
		try {
			Exception e = new Exception("고의로 발생시켰음.");	// 생성자에 메세지 담았음
			throw e;	 // 예외를 발생시킴
		//  throw new Exception("고의로 발생시켰음.");	// 위의 두 줄을 한 줄로

		} catch (Exception e)	{
			System.out.println("에러 메시지 : " + e.getMessage());
			e.printStackTrace();
		}
		System.out.println("프로그램이 정상 종료되었음.");
	}
}
```
output
```java
에러 메시지 : 고의로 발생시켰음.
java.lang.Exception: 고의로 발생시켰음.
	at Ex8_6.main(Ex8_6.java:4)
프로그램이 정상 종료되었음.
```

## checked예외, unchecked예외 
- checked예외: 컴파일러가 예외 처리 여부를 체크(예외 처리 필수)
	- Exception과 그 자손들
	- `try-catch` 필수
- unchecked예외: 컴파일러가 예외 처리 여부를 체크 안함(예외 처리 선택(예외 처리를 안해도 컴파일은 된다는 말임.))
	- RuntimeException과 그 자손들
	- `try-catch` 선택

```java
class Ex8_7 {
	public static void main(String[] args) {
		throw new Exception();		// Exception을 고의로 발생시킨다.
	}
}
```
컴파일에러
```java
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	Unhandled exception type Exception

	at Ex8_7.main(Ex8_7.java:3)
```

<br>

```java
class Ex8_8 {
	public static void main(String[] args) {
		throw new RuntimeException();	// RuntimeException을 고의로 발생시킨다.
	}
}
```
런타임에러
```java
Exception in thread "main" java.lang.RuntimeException
	at Ex8_8.main(Ex8_8.java:3)
```

### 예외를 처리하는 방법
	- try-catch문 (직접 처리)
	- 예외 선언하기 (예외 떠넘기기, 알리기)
	- 은폐 (빈 catch블럭 사용)

## 메서드에 예외 선언하기
	```
	## 오버라이딩의 조건
	1. 선언부가 조상 클래스의 메서드와 일치해야 한다.
		- 선언부 : 반환타입, 메서드이름, 매개변수들
	2. 접근 제어자를 조상 클래스의 메서드보다 좁은 범위로 변경할 수 없다.
	3. 예외는 조상 클래스의 메서드보다 많이 선언할 수 없다.
	```
- 메서드가 호출 시 발생가능한 예외를 호출하는 쪽에 알리는 것
	- 예외를 발생시키는 키워드 `throw`와 예외를 메서드에 선언할 때 쓰이는 `throws`를 잘 구별해야함
```java
void method() throws Exception1, Exception2, ... ExceptionN {

}

// 위의 경우보다 밑의 경우가 선언한 예외가 더 많음
void method() throws Exception {

}
```
예제
```java
static void startInstall() throws SpaceException, MemoryException { 
	if(!enoughSpace()) 		// 충분한 설치 공간이 없으면...
		throw new SpaceException("설치할 공간이 부족합니다.");
	if (!enoughMemory())		// 충분한 메모리가 없으면...
		throw new MemoryException("메모리가 부족합니다.");
} // startInstall메서드의 끝
```
## finally 블럭
- 예외 발생여부와 관계없이 수행되어야 하는 코드를 넣는다.
- finally블럭은 try-catch문의 맨 마지막에 위치해야한다.
- try블럭 안에 return문이 있어서 try블럭을 벗어나갈 경우에도 finally 블럭이 실행된다.
```java
try {
	startInstall();
	copyFiles();
	deleteTempFiles();	// 임시파일 삭제
} catch (Exception e) {
	e.printStackTrace();
	deleteTempFiles();	// 코드의 중복, 꼭 실행되어야하는 문장
}
```
finally블럭 사용
```java
try {
	startInstall();
	copyFiles();
} catch (Exception e) {
	e.printStackTrace();
} finally {
	deleteTempFiles();
}
```
